baseURL = "https://ourrenovators.netlify.com"
languageCode = "en-us"
title = "Our Renovators"
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "robotsTXT", "sitemap", "RSS"]
