baseURL = "https://the-renovators.netlify.com"
languageCode = "en-us"
title = "The Renovators"
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
